baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-055-advanced/"
languageCode = "en-us"
title = "My hugo site"
theme = "simple-style"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
